### ISSUE TITLE
Isomorphic/Universal Rendering

### ISSUE THREAD

**Issue by blooprint** [blooprint/blooprint.xyz#1]
currently having [this](http://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually) problem

**Comment by ddaaggeett** [comment]
currently using [this](https://github.com/caljrimmer/isomorphic-redux-app) as an example

**Comment by ddaaggeett** [comment]
...and done.

**Comment by ddaaggeett** [comment]
**[react-simple-universal](https://github.com/guidsen/react-simple-universal) is even better!**

**Comment by ddaaggeett** [comment]
well - i'm twisting my tongue going back and forth.  i believe it's best to use the following boilerplate:

[isomorphic-redux](https://github.com/bananaoomarang/isomorphic-redux)
tutorial [here](https://medium.com/front-end-developers/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4#.z7icg1mxt)

**Comment by ddaaggeett** [comment]
and then there's this from the redux source examples - **[here](https://github.com/reactjs/redux/tree/master/examples/universal)**

**Comment by ddaaggeett** [comment]
we're using the server side rendering example from [here](https://github.com/reactjs/react-router-redux/tree/master/examples/server)
